options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'neows-extractor'
      - '--gen2'
      - '--region=europe-west1'
      - '--source=.'
      - '--runtime=python312'
      - '--entry-point=main'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'NASA_BASE_URL=projects/$PROJECT_ID/secrets/NASA_BASE_URL:latest,NASA_API_KEY=projects/$PROJECT_ID/secrets/NASA_API_KEY:latest,ASTEROIDS_BUCKET=projects/$PROJECT_ID/secrets/ASTEROIDS_BUCKET:latest'