options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'neows-extractor'
      - '--gen2'
      - '--region=europe-west1'
      - '--source=.'
      - '--runtime=python312'
      - '--entry-point=main'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--set-env-vars=NASA_BASE_URL=https://api.nasa.gov/neo/rest/v1/feed?,ASTEROIDS_BUCKET=astreoids-bucket'
